// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awgfimfvvcrhqrsnmirm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3Z2ZpbWZ2dmNyaHFyc25taXJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0Mzc0MjksImV4cCI6MjA2MjAxMzQyOX0.ahR5-MpxL0UACygWTSGPLVo3el42PzNkFmTNei9SNRM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);